-- ============================================================
-- SEED — run in Supabase SQL Editor (after migration)
-- Source: Google Doc "Action Plan Summary" (Apr 2026)
-- ============================================================
DELETE FROM actions;

INSERT INTO actions (task_id, stage, domain, action_list, owner, kpi, status, archived) VALUES

-- ── Section 1: Business Analysis & Platform ────────────────────────────────

('BA_01',
 'Business Analysis & Platform',
 'Business Analysis',
 'Build tracking and review mechanism — targets system with all key metrics and shared OKRs with XFN teams (Product, GPC)',
 'Boyu',
 'Dashboard with all key metrics including targets (ICP new sign by business type, conversion rates, traffic measurements, shared OKRs). Bi-weekly review with key challenges, reasons, actions and POCs. Daily pushes with key business results.',
 false, false),

('OP_01',
 'Business Analysis & Platform',
 'ICP Operation',
 'Green Path Push and new Push/EDM mechanism product launches — performance monitoring & strategic iteration',
 'Boyu',
 'Push & EDM: Open rate; Product DUV; # of IPV; # high-intent AB; AB Pro #; merchants with AB Pro 5+. Weekly results review (key learnings, why, next steps).',
 false, false),

('OP_02',
 'Business Analysis & Platform',
 'ICP Operation',
 'Search & Recommendation weighting experiments — performance analysis & iterative strategy optimization',
 'Boyu',
 'Weekly results review (key learnings, why and next steps)',
 false, false),

-- ── Section 2: Lead Generation ──────────────────────────

('LG_01',
 'Lead Generation',
 'Lead Gen',
 'Leads tiers with ICP — define and implement lead scoring and tiering framework aligned with ICP criteria',
 'Jinjin',
 'ICP & Tiering proposal delivered',
 true, true),

('LG_02',
 'Lead Generation',
 'Lead Gen',
 'New landing page for leads collection',
 'Jinjin',
 'EU Inbound leads tracker live',
 true, true),

('LG_03',
 'Lead Generation',
 'Lead Gen',
 'AI enrichment tool for leads — automate lead data enrichment to improve qualification accuracy',
 'Jinjin',
 '# of enriched leads; improvement in lead-to-qualified rate',
 false, false),

('LG_04',
 'Lead Generation',
 'Lead Gen',
 'Collaboration with Marketing Team on Tradeshows to collect leads',
 'Jinjin',
 '# of leads collected at tradeshows',
 false, false),

('SH_01',
 'Lead Generation',
 'Lead Gen',
 'Develop Lead Base for Upselling via Shopify implementation; focus Shopify user communication on Alibaba.com ICP; ensure proper translations of funnel and Payoneer for TA. (EU rollout planned post-US launch)',
 'Karl / Arianna',
 '# Free TS; # Orders',
 false, false),

-- ── Section 3: New Customer Acquisition ───────────────────────────

('AC_01',
 'New Customer Acquisition',
 'Acquisition',
 'Lead affiliate partnerships (main focus: Associations of core ICP categories, Unespain for Spain)',
 'Arianna',
 '# of Qualified Leads shared to DS team',
 true, true),

('AC_02',
 'New Customer Acquisition',
 'Acquisition',
 'Handover of Channels from Franci to Ana',
 'Arianna',
 'Handover completed',
 true, true),

('AC_03',
 'New Customer Acquisition',
 'Acquisition',
 'Working on reseller partnership in Italy and Spain / Recovery of partnerships renewed in PT',
 'Arianna',
 '# of New Sign; Cash Revenue; Revenue',
 false, false),

('AC_04',
 'New Customer Acquisition',
 'Acquisition',
 'Amended contract — agreed on changes in Feb; solicited to Borui the amendment to contract in Mar',
 'Arianna',
 '# of Newly Signed Contracts',
 false, false),

('AC_05',
 'New Customer Acquisition',
 'Acquisition',
 'Payment follow-up — discussed solutions with Ella in Feb; follow-up on outstanding payments in Mar',
 'Arianna',
 'Payments resolved',
 false, false),

('PL_01',
 'New Customer Acquisition',
 'Acquisition',
 'Lead affiliate policy (DS / AM / Channels)',
 'Jinjin',
 'Budget approved',
 true, true),

('PL_02',
 'New Customer Acquisition',
 'Acquisition',
 'Commission policy re-definition',
 'Jinjin',
 'Policy officially shared with team',
 true, true),

('PL_03',
 'New Customer Acquisition',
 'Acquisition',
 'Compensation for consumption from FY26',
 'Jinjin',
 'Calculation shared with Leader',
 false, false),

('PL_04',
 'New Customer Acquisition',
 'Acquisition',
 'Commercial products — Packages, Guaranteed Ads, KSP',
 'Jinjin',
 'New Packages presented to teams; Agreement signed on Yida',
 false, false),

('PL_05',
 'New Customer Acquisition',
 'Acquisition',
 'Target assignment for FY26',
 'Jinjin',
 'Targets assigned and communicated',
 false, false),

-- ── Section 4: Customer Success, Buyers & Gov Projects ─────────────────────

('CS_01',
 'Customer Success, Buyers & Gov Projects',
 'CS & AM',
 'Work with Ana on new channel structure pushing differentiated tasks and priorities by channel (e.g. KWA Consumption, KWA Top-Up, TA Activation)',
 'Arianna',
 'Revenue; Renewal Rate',
 false, false),

('BY_01',
 'Customer Success, Buyers & Gov Projects',
 'Buyers',
 'Leverage channels for targeted buyer acquisition — Revolut Business (Accio Work benefit), Italian partner, Atradius, IFEMA (Tradeshow), VISA (Credit Card issuer)',
 'Arianna / Shuxin',
 '# of Buyers acquired',
 false, false),

('BY_02',
 'Customer Success, Buyers & Gov Projects',
 'Buyers',
 'Pilot B2B and B2B2C buyer acquisition model to push local buyer demand — Unespain and various industry players across core categories',
 'Arianna / Shuxin',
 '# of Buyers acquired via pilot model',
 false, false),

('GV_01',
 'Customer Success, Buyers & Gov Projects',
 'Gov (ITA)',
 'ICE (Italy): Agreed on ICE3 conditions (DONE); closing old ICE commission issue impacting channel collaboration (IN PROGRESS); start activity on 303 ICE 3 clients — 94.5% expired pool (PENDING)',
 'Arianna',
 'Cash Revenue (Q1); Revenue (Q2)',
 false, false),

('GV_02',
 'Customer Success, Buyers & Gov Projects',
 'Gov (SPA)',
 'ICEX (Spain): Align with Giusy and Sylvia to secure remaining payments (60%) in Q1',
 'Arianna',
 'Cash Revenue and Revenue (Q1)',
 false, false),

('GV_03',
 'Customer Success, Buyers & Gov Projects',
 'Gov (FRA)',
 'BUSINESS FRANCE (France): Align with Sylvia on BF1 and BF service criticalities (DONE); review Visable involvement with Patrick/Sylvia; align Visable on new ICP and SOP; define new POC for BF payments; work on effective SOP for BF2; process approx. 26 client payments',
 'Arianna',
 'Cash Revenue and Revenue (Q1)',
 false, false);
